<h1><?= $data_admin['name'] ?></h1>



<p><b><?= Session::getFlash() ?></b></p>

<form method="post" enctype="multipart/form-data">
    <label for="title_add_form_bp">Заголовок: </label>
    <input type="text" required name="title" id="title_add_form_bp" value="<?= $addModel->getTitle(); ?>"/> <br/><br/>
    <label for="description_add_form_bp">Краткое описание: </label>
    <textarea name="description" id="description_add_form_bp" cols="30" rows="10"><?=$addModel->getAdditionalFieldsValueArr()['description']; ?></textarea><br/><br/>
    <label for="text_add_form_bp">Текст страници: </label>
    <textarea name="text" id="text_add_form_bp" cols="30" rows="10"><?=$addModel->getAdditionalFieldsValueArr()['text']; ?></textarea><br/><br/>


    <input type="hidden" name="MAX_FILE_SIZE" value=2000000>
    <p>Загружаемое изображение не должно превышать объем больше 2 мб и размер не менее 945х250px. Если загружаемое изображение
        имеет размеры более 945х250px оно будет обрезано в процессе загрузки до необходимого размера </p>
    <label for="file_add_form_bp">Изображение: </label>
    <input id="file_add_form_bp" name="userfile" type="file">

    <p>Если поставить галочку - без меню - документ не будет доступен в главном меню</p></br>
    <label for="without_menu_add_form_bp">Без меню</label>
    <input type="checkbox" id="without_menu_add_form_bp" name="without_menu"/> <br/><br/>

    <p>Если указать название пункта меню, адрес (псевдоним) документа будет сформирован на основе этого названия
        Если оставить поле пустым адрес (псевдоним) документа, а также название пункта меню будут сформированы на основе
        заголовка</p></br>
    <label for="menu_name_add_form_bp">Название пункта меню: </label>
    <input type="text" id="menu_name_add_form_bp" name="menu_name" value="<?= $addModel->getMenuName(); ?>"/> <br/><br/>
    <label for="menuselect_add_form_bp">Родительский пункт меню: </label>
    <select name="menu" id="menuselect_add_form_bp">
        <option value="">Главное меню</option>
        <?php Controller::recurs_render_menu_in_form($data_menu) ?>
    </select><br/><br/>
    <label for="publication_add_form_bp">Опубликованно: </label>
    <input type="checkbox" checked id="publication_add_form_bp" name="publication"/> <br/><br/>
    <input type="hidden" name="redirect" value="/admin/materials">
    <input type="submit" value="Сохранить"/>
</form>

<?php if($redirect_status){
    isset($redirect)? Controller::redirect($redirect): null;
}
?>
