<h1> Радактирование <?= $data_page[0]['title'] ?></h1>




<p><b><?= Session::getFlash() ?></b></p>



<form method="post" enctype="multipart/form-data">
    <label for="title_edit_form_bp">Заголовок: </label>
    <input type="text" required name="title" id="title_edit_form_bp" value="<?= $edit_model->getTitle() ? $edit_model->getTitle() : $data_page[0]['title']; ?>"/> <br/><br/>
    <label for="description_edit_form_bp">Краткое описание: </label>
    <p>Текс должно содержать не более 600 символов. Если текст краткого описания привысит лимит
    текст будет обрезан по 600 символу и добавлено троеточие.</p>
    <textarea name="description" id="description_edit_form_bp" cols="30" rows="10"><?= isset($edit_model->getAdditionalFieldsValueArr()['description']) ? $edit_model->getAdditionalFieldsValueArr()['description'] : $data_page[0]['description']; ?></textarea><br/><br/>

    <label for="text_edit_form_bp">Текст страници: </label>
    <textarea name="text" id="text_edit_form_bp" cols="30" rows="10"><?= isset($edit_model->getAdditionalFieldsValueArr()['text']) ? $edit_model->getAdditionalFieldsValueArr()['text'] : $data_page[0]['text']; ?></textarea><br/><br/>
    <p>Два способа вставки изображений в хедере (на верху страницы). Первый вариант - "Загрузить изображение" - загрузка изображение с локального
        компьютера. Второй вариант - "Вставить изображение" - выбор изображения из списка уже загруженных ранее, и используются
        другими текстовыми документами. Хранятся на сервере. В доступном списке отображаются только те изображения размеры
        которых составляют 945х250 px
        Если будут выбранны изображения двумя способами то в документе будет сохранено изображение полученное методом - "Загрузить изображение".
    </p>
    <div>
    <input type="hidden" name="MAX_FILE_SIZE" value=500000>
    <p>Загружаемое изображение не должно превышать объем больше 0,5 мб и размер не менее 945х250px. Если загружаемое изображение
        имеет размеры более 945х250px оно будет обрезано в процессе загрузки до необходимого размера </p>
    <label for="file_add_form_bp">Загрузить изображение: </label>
    <input id="file_add_form_bp" name="userfile" type="file">
    <img src="/<?= $edit_model->getImg($id) ?>" alt=""/>
    </div>
    <div>
        <label for="img_server">Вставить изображение: </label>
        <input type="text" name="file_server" id="img_server" size="20" value="" readonly/>
        <input type="button" id="browse" name="browse" value="Выбрать файл"/>
    </div>

    <p>Если поставить галочку - без меню - документ не будет доступен в главном меню</p></br>
    <label for="without_menu_edit_form_bp">Без меню</label>
    <input type="checkbox" id="without_menu_edit_form_bp" name="without_menu"/> <br/><br/>

    <p>Если указать название пункта меню, адрес (псевдоним) документа будет сформирован на основе этого названия
        Если оставить поле пустым адрес (псевдоним) документа, а также название пункта меню будут сформированы на основе
        заголовка</p></br>
    <label for="menu_name_edit_form_bp">Название пункта меню: </label>
    <input type="text" id="menu_name_edit_form_bp" name="menu_name" value="<?= isset($data_menu_item[0]['name_menu_item'])? $data_menu_item[0]['name_menu_item'] : '' ?>"/> <br/><br/>
    <label for="menuselect_edit_form_bp">Родительский пункт меню: </label>
    <select name="menu" id="menuselect_edit_form_bp">
        <option value="">Главное меню</option>
        <?php Controller::recurs_render_menu_in_form($data_menu, $data_menu_item) ?>
    </select><br/><br/>
    <label for="publication_edit_form_bp">Опубликованно: </label>
    <input type="checkbox" checked id="publication_edit_form_bp" name="publication"/> <br/><br/>
    <input type="hidden" name="redirect" value="/admin/materials"/>
    <input type="submit" value="Сохранить"/>
</form>

<?php if($redirect_status){
    isset($redirect)? Controller::redirect($redirect): null;
}
?>