<form  method="get">
    <label for="totallist">Элементов на странице:</label>
    <select name="<?= $params1 ?>" id="totallist">
        <?php foreach(Config::get('elements_per_page') as $v): ?>
            <option <?= $params2 == $v ? 'selected' : '' ?> value="<?= $v ?>"><?= $v == 10000 ? 'All' : $v ?></option>
        <?php endforeach ?>
    </select>
    <input type="hidden" name="page" value="1"/>
    <input type="submit" value="Применить"/>
</form>
