<h1><?= $data_admin['name'] ?></h1>

<?= Controller::render_simple(VIEW_DIR . 'Admin/elements_per_page.phtml','translation_per_page'); ?>

<table border="1">
    <tr>

        <td>Ключ</td>
        <td>Украинский</td>
        <td>Изменить укр.</td>
        <td>Английский</td>
        <td>Изменить англ.</td>
    </tr>
    <?php foreach($data_materials as $k => $v): ?>
        <tr>

            <td><?= $k ?></td>
            <td><?= $v['en']?></td>
            <td></td>
            <td><?= $v['uk']?></td>
            <td></td>
        </tr>
    <?php endforeach ?>
</table>
<?= Controller::render_simple(VIEW_DIR . 'Admin/pagination.phtml',$data_pagination,$data_url,$data_materials, 'translation_per_page'); ?>
