<h1><?= $data_admin['name'] ?></h1>



<?= Controller::render_simple(VIEW_DIR . 'Admin/elements_per_page.phtml','log_per_page', $items_per_page); ?>

<table border="1">
    <tr>
        <td>№</td>
        <td>Дата</td>
        <td>Код ошибки</td>
        <td>Сообщение</td>
        <td>Файл</td>
        <td>Строка</td>
    </tr>
    <?php if($data_materials):
    foreach ($data_materials as $k => $v): ?>
        <tr>
            <td><?= $k+1 ?></td>
            <td><?= $v['0']?></td>
            <td><?= $v['1']?></td>
            <td><?= $v['2']?></td>
            <td><?= $v['3']?></td>
            <td><?= $v['4']?></td>
        </tr>
    <?php endforeach;
    endif ?>
</table>

<?= Controller::render_simple(VIEW_DIR . 'Admin/pagination.phtml',$data_pagination,$data_url,$data_materials,'log_per_page'); ?>