<h1> <?= $data_admin['name'] ?></h1>

<?= Controller::render_simple(VIEW_DIR . 'Admin/elements_per_page.phtml','materials_per_page'); ?>


<table border="1">
    <tr>
        <td>id</td>
        <td>Тип материала</td>
        <td>Опубликовано/</br>Не опубликовано</td>
        <td>Укр.</br> материал</td>
        <td>Редактировать</br> укр</td>
        <td>Удалить</br> укр</td>
        <td>Добавить</br> перевод</td>
        <td>Англ.</br> материал</td>
        <td>Редактировать</br> англ</td>
        <td>Удалить </br>англ</td>
    </tr>
<?php  foreach($data_materials as $k => $v): ?>
        <tr>
            <td><?= $v['id'] ?></td>
            <td><?= $v['type_materials'] ?></td>
            <td><?= $v['status'] ?></td>
            <td><?= $v['title_uk'] ?></td>
            <td></td>
            <td></td>
            <td></td>
            <td><?= $v['title_en'] ?></td>
            <td></td>
            <td></td>
        </tr>
<?php endforeach ?>
</table>
<?= Controller::render_simple(VIEW_DIR . 'Admin/pagination.phtml',$data_pagination,$data_url,$data_materials, 'materials_per_page'); ?>

