<?php Debugger::PrintR($data_materials);
echo $data_url;  ?>

<h1> <?= $data_admin['name'] ?></h1>

<?= Controller::render_simple(VIEW_DIR . 'Admin/elements_per_page.phtml','materials_per_page'); ?>



<?php foreach($type_of_materials as $v):
    if($v != 'admin'):?>
        <a  href="/admin/add_<?= $v ?>">Добавить <?= $v ?></a>
<?php endif ?>
<?php endforeach ?>


<table border="1">
    <tr>
        <td>id</td>
        <td>Тип материала</td>
        <td>Опубликовано/</br>Не опубликовано</td>
        <td>Укр.</br> материал</td>
        <td>Редактировать</br> укр</td>

        <td>Добавить</br> перевод</td>
        <td>Англ.</br> материал</td>
        <td>Редактировать</br> англ</td>
        <td>Удалить </br>материал</td>
    </tr>
<?php  foreach($data_materials as $k => $v): ?>
        <tr>
            <td><?= $v['id'] ?></td>
            <td><?= $v['type_materials'] ?></td>
            <td><?= $v['status'] ?></td>
            <td><a href="/<?= $v['alias_uk'] ?>"><?= $v['title_uk'] ?></a></td>
            <td><a href="/admin/edit/<?= strtolower($v['type_materials']) ?>/<?= $v['alias_uk'] ?>">Редактировать</a></td>
            <td></td>
            <td><?= $v['title_en'] ?></td>
            <td></td>
            <td><a href="/admin/delete/<?= $v['alias_uk'] ?>">Удалить материал</a></td>
        </tr>
<?php endforeach ?>
</table>
<?= Controller::render_simple(VIEW_DIR . 'Admin/pagination.phtml',$data_pagination,$data_url,$data_materials, 'materials_per_page'); ?>

