<h1><?= $data_page['title'] ?></h1>
<p><?= Session::getFlash() ?></p>

<form method="post">
    <?php if(!Session::has('user')): ?>
    <?= __t('name') ?> <input type="text" name="name" value="<?=$form->name?>"> <br>
    Email: <input type="email" name="email" value="<?=$form->email?>"> <br>
    <?php endif ?>
    <?= __t('message') ?> <textarea name="message" id="" cols="30" rows="10"><?=$form->message?></textarea>
    <input type="hidden" name="date" value="<?= date('Y-m-d H:i:s')?>">
    <button type="submit"><?= __t('submit') ?></button>
</form>
