<h1><?= $data_page['title'] ?></h1>

<p><?= $data_page['text'] ?></p>




    <?php foreach($data_news as $k => $v): ?>
    <div>
    <h2><?= $v['title']?></h2>
    <p><?= $v['description']?></p>
    <a href="/<?= $lang.$v['alias'] ?>"><?= __t('read_more')?></a>
    </div>

    <?php endforeach ?>

<?= Controller::render_simple(VIEW_DIR . 'Admin/pagination.phtml', $data_pagination, $data_url, $data_news, 'news_per_page'); ?>
