<h1><?= $data_page['title'] ?></h1>

<p><?= $data_page['text'] ?></p>


<?php foreach ($data_news as $k => $v):
    if ($v['title']):
        ?>
        <div class="news_views">
            <h2><a href="/<?= $lang . $v['alias'] ?>"><?= $v['title']?></a></h2>

            <p><?= $v['short_text']?></p>
            <p><?= $lang . $v['date'] ?></p>
            <a href="/<?= $lang . $v['alias'] ?>"><?= __t('read_more')?></a>
        </div>
    <?php endif ?>

<?php endforeach ?>

<?= Controller::render_simple(VIEW_DIR . 'Admin/pagination.phtml', $data_pagination, $data_url, $data_news, 'news_per_page'); ?>
