<div class="sidebar_inner">
    <h2><?= __t('menu_section') ?></h2>
<?php MenuController::menu_recurs($block_menu, 'class="menu_block"', 'active_page' );

//Debugger::PrintR($block_menu);

//Debugger::PrintR(MenuController::getMainMenuArray());

//MenuController::getById(MenuController::getMainMenuArray(), 10);

//Debugger::PrintR(MenuController::getMainMenuPart());

//Debugger::PrintR(MenuController::getById(MenuController::getMainMenuArray(), 218));

?>
</div>