
<?php MenuController::menu_recurs($args, 'id="main-menu" class="sm sm-blue"');

//Debugger::PrintR(MenuController::getMainMenuArray());

//MenuController::getById(MenuController::getMainMenuArray(), 10);

//Debugger::PrintR(MenuController::getMainMenuPart());
///$test = MenuController::getMainMenuPart()['child'];

///MenuController::IdArray($test);
///Debugger::PrintR(MenuController::getIdArray());

//$test = new MenuController();
//$arr = $test->getBlockMainMenuAction();
//Debugger::PrintR($arr);

//Debugger::PrintR(MenuController::getById(MenuController::getMainMenuArray(), 218));



//$test = new MenuController();
//$t = $test->getBlockMainMenuAction();
//Debugger::PrintR($t);

?>

