<b><?= Session::getFlash(); ?></b>
<div class="contact_form login_form col-xs-offset-4 col-sm-offset-4 col-md-offset-4">
    <form method="post">
        <div class="row">
            <div class="col-xs-3 col-sm-3 col-md-3">
                <label for="name_login"><?= __t('username')?>:</label>
            </div>
            <div>
                <input type="text" id="name_login" name="username" value="<?= $login->getUsername(); ?>"/>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3 col-sm-3 col-md-3">
                <label for="password_login"><?= __t('password')?>:</label>
            </div>
            <div>
                <input type="password" id="password_login" name="password"/>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3 col-sm-3 col-md-3">
                <input type="submit" class="search_button" value="<?= __t('submit') ?>"/>
            </div>
        </div>

    </form>
</div>