<!doctype html>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <script type="text/javascript" src="/Webroot/plagins/ckeditor_mono/ckeditor.js"></script>
    <title><?=Config::get('site_name') ?></title>
</head>
<body>



<hr/>
<?= Router::getId() != 17 ? $admin_menu : null ?>

<hr/>

<?= Router::getId()?></br>
<?= Router::getUri()?>

<?=$content?>
<?= Router::getId() == 17 ? $admin_menu : null ?>


<script type="text/javascript">
    CKEDITOR.replace("text",{'filebrowserBrowseUrl':'/Webroot/plagins/ckeditor_mono/kcfinder/browse.php?type=files',
        'filebrowserImageBrowseUrl':'/Webroot/plagins/ckeditor_mono/kcfinder/browse.php?type=images',
        'filebrowserFlashBrowseUrl':'/Webroot/plagins/ckeditor_mono/kcfinder/browse.php?type=flash',
        'filebrowserUploadUrl':'/Webroot/plagins/ckeditor_mono/kcfinder/upload.php?type=files',
        'filebrowserImageUploadUrl':'/Webroot/plagins/ckeditor_mono/kcfinder/upload.php?type=images',
        'filebrowserFlashUploadUrl':'/Webroot/plagins/ckeditor_mono/kcfinder/upload.php?type=flash'});
    CKEDITOR.replace("description",{'filebrowserBrowseUrl':'/Webroot/plagins/ckeditor_mono/kcfinder/browse.php?type=files',
        'filebrowserImageBrowseUrl':'/Webroot/plagins/ckeditor_mono/kcfinder/browse.php?type=images',
        'filebrowserFlashBrowseUrl':'/Webroot/plagins/ckeditor_mono/kcfinder/browse.php?type=flash',
        'filebrowserUploadUrl':'/Webroot/plagins/ckeditor_mono/kcfinder/upload.php?type=files',
        'filebrowserImageUploadUrl':'/Webroot/plagins/ckeditor_mono/kcfinder/upload.php?type=images',
        'filebrowserFlashUploadUrl':'/Webroot/plagins/ckeditor_mono/kcfinder/upload.php?type=flash'});
</script>
<script type="text/javascript" src="/Webroot/plagins/smartmenus/libs/jquery/jquery.js"></script>
<script type="text/javascript" src="/Webroot/js/jquery.DOMWindow.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $('#browse*').openDOMWindow({
            height: 400,
            width: 550,
            eventType: 'click',
            loader: 1,
            loaderImagePath: '',
            loaderHeight: 16,
            loaderWidth: 17,
            windowSource: 'ajax',
            windowSourceURL: '/Webroot/DomWindow.php',
            windowHTTPType: 'get'
        });
    });
</script>
</body>
</html>