<!DOCTYPE html>
<!--[if lt IE 7]>
<html lang="ru" class="lt-ie9 lt-ie8 lt-ie7"><![endif]-->
<!--[if IE 7]>
<html lang="ru" class="lt-ie9 lt-ie8"><![endif]-->
<!--[if IE 8]>
<html lang="ru" class="lt-ie9"><![endif]-->
<!--[if gt IE 8]><!-->
<html lang="ru">
<!--<![endif]-->
<head>

    <meta charset="UTF-8"/>
    <meta name="description" content=""/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="/Webroot/plagins/bootstrap/bootstrap-grid-3.3.1.min.css"/>
    <link rel="stylesheet" href="/Webroot/plagins/bootstrap/bootstrap.min.css"/>
    <link rel="stylesheet" href="/Webroot/plagins/font-awesome-4.2.0/css/font-awesome.min.css"/>

    <link rel="stylesheet" href="/Webroot/plagins/owl-carousel/owl.carousel.css"/>
    <link rel="stylesheet" href="/Webroot/plagins/countdown/jquery.countdown.css"/>
    <link rel="stylesheet" href="/Webroot/css/css_reset.css"/>
    <link rel="stylesheet" href="/Webroot/css/fonts.css"/>
    <link rel="stylesheet" href="/Webroot/css/main.css"/>
    <link rel="stylesheet" href="/Webroot/css/media.css"/>
</head>
<body>
<?= $content ?>
</body>
</html>