<!doctype html>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <title><?=Config::get('site_name') ?></title>
</head>
<body>


<?= $main_menu?>

<hr/>
<?= $lang_icon; ?>
<hr/>
<?= $bread_crumbs; ?>

<hr/>
<?= $login_logout_block; ?>
<hr/>

<p>Статический текст: <?= __t('testovii_tekst')?></p>

<hr/>
<?='id: '. Router::getId()?></br>
<?='Url: '. Router::getUri()?></br>
<?= 'action: '.Router::getAction()?></br>
<?='controller: '. Router::getController()?></br>
<?='lang: '. Router::getLanguage()?></br>
<?='rout: '. Router::getRout()?></br>
<?php'url_arr: '. Debugger::PrintR(Router::getUrlArray());  ?></br>


<?=$content?>

</body>
</html>