<!doctype html>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <title><?=Config::get('site_name') ?></title>
</head>
<body>
<a href="/index/index?id=1">Home</a>
<a href="/index/test?id=2">About</a>
<a href="index.php?rout=index/contact&id=3">Contacts</a>
<a href="index.php?rout=book/index&id=4">Books</a>
<hr/>


<?php if(Router::getLanguage() == 'uk'):?>
<a href="<?= Lang::url_translation('en')?>">EN</a>
<?php elseif(Router::getLanguage() == 'en'): ?>
<a href="<?= Lang::url_translation('uk')?>">UK</a>
<?php endif; ?>
<hr/>

<?=$content?>

</body>
</html>